#### Day 17
    1. Continue to Oops
        a. Data Encapsulation (Data hiding) in python
        b. Polymorphism (Method overloading and method overriding)
        c. Data Abstraction.
    2. Data science packages
        a. Numpy
        b. Pandas
        c. Matplotlib

###### Difference between Data Encapsulation and Data Hiding:
    Encapsulation means wraping the implementation of data member and methods inside the class
    
    Its just envoleping the complexity of data
    Data Hiding means protecting the members of a class
    From an illegal and unauthorized users.

##### Data Hiding:
    It means making the data private so that data will not be accesable by the others
    It can be accessed only in the class where it is declared.
Note: To make class variable as private by using double underscore

In [4]:
class Myclass:
    __a=10         ##private variable
    def add(self,b):
        sum=self.__a+b
        print(sum)
ob=Myclass()
ob.add(20)  ##Its just accessing the method of class
print(ob.__a)

30


AttributeError: 'Myclass' object has no attribute '__a'

#### Polymorphism in Oops:
    Its a Greek word
        poly  -> many
        morph -> having many forms
    It refers to the functions having the same names but carrying out different funtionalities

In [7]:
class audi:
    def desc(self):
        print("This is desc of AUDI CAR")
class BMW:
    def desc(self):
        print("This is desc of BMW CAR")
a=audi()
b=BMW()
for car in(a,b):
    car.desc()

This is desc of AUDI CAR
This is desc of BMW CAR


##### Data Abstraction:
    We use absraction in oops for hiding the internal details or implementations of functions and functionalities only
Note:
    
    Any class with atleast one abstract function is called as abstract class.
    To create an abstract class
        we need to import ABC class from abc module.
        ABS stands for Abstract Base Class.
    Data abstraction can be done using inheritance

##### syntax for how to import ABS Class
    from abc import ABC
    class Abs_class(ABC):
        #body of the class
        @abstract method

In [20]:
from abc import ABC,abstractmethod

class car(ABC):               #abstract class
    def __init__(self,name):
        self.name=name
    
    def desc(self):           #normal class method
        print("This is desc of class car")
    
    @abstractmethod          #abstract method
    def price(self,x):
        pass

class new(car):
    def price(self,x):
        print(f"The{self.name}'s price is {x} lakhs")

ob=new("BMW")   #child class object
ob.desc() 
ob.price(50)

This is desc of class car
TheBMW's price is 50 lakhs


###### Data Science Packages
            1. Numpy(Num+py)
               Numerical data + python
            2. Pandas - Its used packages used for
                a. Data Manipulation (Modification,updation)
                b. Data Analysis (To know the complete knowledge about data including the theme of datasets)
                c. Data Cleaning (To remove unnecessary data from data sets.)
            3. Matplotlib - To represent complex data with 2d- Graphics tools.
                1. Plots
                2. Bar Graphs
                3. Pie Charts
                4. Histograms
                5. Scatter plots
                6. Area graphs

##### Numpys in python:
    Numpy is open source library package used for scientific computing.
    Its mainly deals with
        a. Mathematical data
        b. Scientific data
        c. Engineering data
        d. Statistical data
        e. Multi-dimensional arrays and matric multiplication.
Note: Numpy contains a powerful n-dimensional array object.

###### How to install numpy package?
    pip install numpy
###### How to impact and use numpy package?
    import numpy as np

In [23]:
#How to create numpy arrays?
import numpy as np
a=np.array([1,2,3])   #single-dimensional numpy array
a

array([1, 2, 3])

In [24]:
#To know the shape of array
a.shape

(3,)

In [27]:
#How to 2D- Multi dimensional arrays:
a=np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a.shape

(2, 3)

In [29]:
#Numpy array attributes:
a1=np.array([1,2,3,4,5,6,7,8,9])
print(a1)
a2=np.array([2.3,6,9,3.5,9.0,1.3])
print(a2)
print(a1.dtype)
print(a2.dtype)

[1 2 3 4 5 6 7 8 9]
[2.3 6.  9.  3.5 9.  1.3]
int32
float64


In [31]:
a1=np.array([1,2,3,4,5,6,7,8,9])   #1-D array
a2=np.array([[1,2,3],[4,5,6]])     #2-D array
a3=np.array([[[1,3,5],[5,6,7]],[[8,9,3],[6,7,8]]]) #3-D array
print(a1.shape)
print(a2.shape)
print(a3.shape)

(9,)
(2, 3)
(2, 2, 3)


In [32]:
#Dimension of an numpy:
#ndim():
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [33]:
#Reshape of array:
a1=np.array([1,2,3,4,5,6,7,8])
print(a1.shape)
print("Before Reshape",a1)
a2=a1.reshape(2,4)
##a2=a1.reshape(2,5) #value error
print("After Reshape",a2)
print(a2.shape)

(8,)
Before Reshape [1 2 3 4 5 6 7 8]
After Reshape [[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [42]:
a1=np.array([1,2,3,4,5,6,7,8,9])
print(a1,a1.shape,sep="\n")
a2=a1.reshape(3,3)
print(a2,a2.shape,sep="\n")

[1 2 3 4 5 6 7 8 9]
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [44]:
#Resize of array : (it modoifies existing shape and array itself)
a1=np.array([1,2,3,4,5,6,7,8])
print(a1)
a1.resize(5)  ##slicing 
print(a1)
a1.resize(2,4)
print(a1)
a1.resize(3,3)
print(a1)
a1.resize(5,3)
print(a1)

[1 2 3 4 5 6 7 8]
[1 2 3 4 5]
[[1 2 3 4]
 [5 0 0 0]]
[[1 2 3]
 [4 5 0]
 [0 0 0]]
[[1 2 3]
 [4 5 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


We have 4 types of arrays

    1. Zero array
    2. One array
    3. Eye array (diagonal array)
    4. Full array

In [48]:
##creating zero array
import numpy as np
a1=np.zeros(3)
a2=np.zeros((2,4),dtype="int64")
print(a1.dtype)
print(a2.dtype)
print(a1,a2,sep="\n")

float64
int64
[0. 0. 0.]
[[0 0 0 0]
 [0 0 0 0]]


In [49]:
##creating ones array:
a1=np.ones(3,dtype="int64")
a2=np.ones((6,5),dtype="int64")
print(a1.dtype)
print(a2.dtype)
print(a1,a2,sep="\n")

int64
int64
[1 1 1]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [55]:
##Creating full array:
### syntax: full(dimension,specified number)
np.full(3,100)
np.full((3,9),500)
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [63]:
##creating eye array:
np.eye(6,dtype="int64")
np.eye(5,k=0,dtype="int64")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int64)

In [1]:
pip install nbconvert

Note: you may need to restart the kernel to use updated packages.
